name: Check_If_Registry_key_Value_Exist
description: Check if files or registry key exist
parameters:
  actions:
    configuration:
      check_registry_exist_3e0e47d3:
        properties:
          keys:
            required: true
          values:
            required: true
  conditions:
    platform_is_equal_to_windows_host_groups_includes_to_parameterized_hostname_includes_to_parameterize_02ba0c09:
      fields:
        get_device_details_d2e382bd.Device.GetDetails.Groups:
          required: false
          multiple: true
          operator: IN
        device_query_78798221.Device.query.devices.#:
          required: false
          multiple: true
          operator: IN
  trigger:
    node_id: trigger
    fields:
      timer_event_definition:
        required: true
trigger:
  next:
    - update_job_history_1c5df989
  event: Schedule
actions:
  device_query_78798221:
    next:
      - activity_78798221_1b8a_4d0b_87b0_eb0ca0ec645c_device_query_devices_4ab24f5e
    id: 68ffa99af40c84b36462daa076f535d0
    properties:
      device_status: all
  update_job_history_1c5df989:
    next:
      - device_query_78798221
    id: functions.job_history.update_job_history
    properties:
      definition_name: "${Workflow.Definition.Name}"
      execution_id: "${Workflow.Execution.ID}"
      execution_timestamp: "${Workflow.Execution.Time}"
      status: In Progress
loops:
  activity_78798221_1b8a_4d0b_87b0_eb0ca0ec645c_device_query_devices_4ab24f5e:
    for:
      input: device_query_78798221.Device.query.devices
      continue_on_partial_execution: true
    trigger:
      next:
        - get_device_details_d2e382bd
    actions:
      check_registry_exist_3e0e47d3:
        next:
          - write_data_into_logscale_1b5e148b
        id: rtr_scripts.Check_Registry_Exist
        properties:
          device_id: "${device_query_78798221.Device.query.devices.#}"
      get_device_details_d2e382bd:
        next:
          - platform_is_equal_to_windows_host_groups_includes_to_parameterized_hostname_includes_to_parameterize_02ba0c09
        id: 6265dc947cc2252f74a5f25261ac36a9
        properties:
          device_id: "${device_query_78798221.Device.query.devices.#}"
      write_data_into_logscale_1b5e148b:
        id: 0ec68880256f6192b9abef766d31fb04
        properties:
          _fields:
            - "${check_registry_exist_3e0e47d3.RTR.App_Check_Registry_Exist.stdout}"
            - "${get_device_details_d2e382bd.Device.GetDetails.Domain}"
            - "${get_device_details_d2e382bd.Device.GetDetails.Groups}"
            - "${get_device_details_d2e382bd.Device.GetDetails.Hostname}"
            - "${Workflow.Execution.ID}"
            - "${device_query_78798221.Device.query.devices.#}"
            - "${get_device_details_d2e382bd.Device.GetDetails.Platform}"
            - "${Workflow.Execution.Time}"
            - "${Workflow.Definition.Name}"
            - "${Trigger.Category.Schedule.}"
            - "${Trigger.CID}"
          foundry_app_id: ${{FOUNDRY_APP_ID}}
    conditions:
      platform_is_equal_to_windows_host_groups_includes_to_parameterized_hostname_includes_to_parameterize_02ba0c09:
        next:
          - check_registry_exist_3e0e47d3
        expression: get_device_details_d2e382bd.Device.GetDetails.Platform:'Windows'
        display:
            - Platform is equal to Windows
            - Host groups includes to [parameterized]
            - Hostname includes to [parameterized]
